# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IGListKit', '~> 3.0'
  pod 'Moya'
  pod 'PINRemoteImage', '3.0.0-beta.12'


end
