//
//  MainRouter.swift
//  WeatherDemo
//
//  Created by Dima Tsurkan on 9/21/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainRoutingLogic {
    func routeToSettings()
}

protocol MainDataPassing {
    var dataStore: MainDataStore? { get }
}

class MainRouter: NSObject, MainRoutingLogic, MainDataPassing {
    weak var viewController: MainViewController?
    var dataStore: MainDataStore?
  
    // MARK: Routing
  
    func routeToSettings() {
        let destinationVC = SettingsViewController()
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSettings(source: dataStore!, destination: &destinationDS)
        navigateToSettings(source: viewController!, destination: destinationVC)
    }
    

    // MARK: Navigation
  
    func navigateToSettings(source: MainViewController, destination: SettingsViewController) {
      source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
  
    func passDataToSettings(source: MainDataStore, destination: inout SettingsDataStore) {
      
    }
}
