//
//  MainPresenter.swift
//  WeatherDemo
//
//  Created by Dima Tsurkan on 9/21/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentCurrentWeather(response: Main.CurrentWeaher.Response)
    func presentForecast(response: Main.Forecast.Response)
    func presentError(response: Main.CurrentWeaher.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
  
    // MARK: - Present Current Weather
  
    func presentCurrentWeather(response: Main.CurrentWeaher.Response) {
        let displayedWeather = Main.CurrentWeaher.ViewModel.DisplayedWeather(id: (response.weather?.id)!, weather: response.weather!)
        let viewModel = Main.CurrentWeaher.ViewModel(displayedWeather: displayedWeather)
        viewController?.displayCurrentWeather(viewModel: viewModel)
    }
    
    func presentForecast(response: Main.Forecast.Response) {
        var displayedForecasts: [Main.Forecast.ViewModel.DisplayedForecast] = []
//        for weather in response.forecast! {
//            let displayedForecast = Main.Forecast.ViewModel.DisplayedForecast(id: weather.id, forecast: weather)
//            displayedForecasts.append(displayedForecast)
//        }
//        let viewModel = Main.Forecast.ViewModel(displayedForecast: displayedForecasts)
//        viewController?.displayForecast(viewModel: viewModel)
    }
    
    func presentError(response: Main.CurrentWeaher.Response) {
        debugPrint(response.errorDescription!)
    }
}
