//
//  SettingsRouter.swift
//  WeatherDemo
//
//  Created by Dima Tsurkan on 9/21/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
    func routeToLanguages()
}

protocol SettingsDataPassing {
    var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing {
    weak var viewController: SettingsViewController?
    var dataStore: SettingsDataStore?
  
    // MARK: Routing
  
    func routeToLanguages() {
        let destinationVC = LanguagesViewController()
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

    // MARK: Navigation
  
    func navigateToSomewhere(source: SettingsViewController, destination: LanguagesViewController) {
      source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
  
    //func passDataToSomewhere(source: SettingsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
