//
//  SettingsInteractor.swift
//  WeatherDemo
//
//  Created by Dima Tsurkan on 9/21/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsBusinessLogic {
    func doSomething(request: Settings.Something.Request)
}

protocol SettingsDataStore {
    //var name: String { get set }
}

class SettingsInteractor: SettingsBusinessLogic, SettingsDataStore {
    var presenter: SettingsPresentationLogic?
    var worker: SettingsWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: Settings.Something.Request) {
        worker = SettingsWorker()
        worker?.doSomeWork()
    
        let response = Settings.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
